### ISSUE TITLE
Post the american gut consent form

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#113]
URL to use:

http://microbio.me/agconsent

just make the consent form document the default for that directory.

**Comment by rob-knight** [comment]
Thanks!

On Jan 24, 2013, at 2:02 PM, "Doug Wendel" <notifications@github.com<mailto:notifications@github.com>> wrote:

URL to use:

http://microbio.me/agconsent

just make the consent form document the default for that directory.

**Comment by douginator2000** [comment]
Form has been posted to:

http://microbio.me/agconsent
