### ISSUE TITLE
Old and invalid loading jobs can appear when "process" is clicked.

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#14]
When submitting job to qiime, old loading links can still re-appear if they were not also cleared previously. To replicate this issue, process a study, note the loading links that appear when processing has happened successfully, then re-process the study (by clearing only the process links, not the loading links). As soon as you click process, the old loading links will reappear.

**Comment by adamrp** [comment]
@ElDeveloper I think this is resolved, right?

**Comment by ElDeveloper** [comment]
Yes, I have not seen this in a while.
