### ISSUE TITLE
Sequence counts and sample summary information unclear

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#144]
E.g., for study 721, the "total sequence count" is listed as 22302948, but this number does not match the number of raw sequences (87507177), the number of sequences after split_libraries (21866641), or the number of sequences that get clustered (20131358).

Also, the heading "total OTU count" is misleading, as it suggests that there are that number of OTUs (in reality, the number listed under that heading seems to be the number of _sequences_ that are assigned to OTUs)

**Comment by douginator2000** [comment]
Raw sequences wil never be meaningful in this grid. Where are you getting the counts from for the other figures? The current code reads the split_library_log file and pulls sequence counts per sample.

RE: OTU text - good point, it should probably read "OTUs Assigned" or something.

**Comment by adamrp** [comment]
Daniel was curious about raw sequences, which is why I was looking in the first place, but understand that including that number here may be unnecessary/confusing to users.

I got the number of raw reads from the sequence files (this information is also available in the split_libraries_log files of course):

for i in `/bin/ls *_barcodes.fastq.gz`; do echo $i; zcat $i | grep -c '^@'; done

I used the following simple python function to count sequences that passed split_libraries:

> > > def sum_counts(lines):
> > > ...     s = 0
> > > ...     for line in lines:
> > > ...             s += int(line.split()[-1])
> > > ...     return s

and I looked at the per_library_stats output to count sequences that were assigned to OTUs:

for i in `seq 1 8`; do echo $i; per_library_stats.py -i processed_data_s_${i}_2_sequence_/gg_97_otus/exact_uclust_ref_otu_table.biom | grep 'Num observations'; done

**Comment by adamrp** [comment]
My mistake -- copy/paste error led to a miscounting of sequences in split_libraries_log!  "total sequence count" does appear to be in fact the number of sequences that pass split_libraries/quality filtering

**Comment by adamrp** [comment]
w.r.t. the "OTU Count" heading, I think "OTUs Assigned" is also a little misleading... maybe "Total Sequences Assigned to Greengenes OTUs" (perhaps including the Greengenes version) would be more explicit?

**Comment by douginator2000** [comment]
Makes sense but is a little long for a table header - shorter suggestions?

On Wednesday, February 27, 2013, adamrp wrote:

> w.r.t. the "OTU Count" heading, I think "OTUs Assigned" is also a little
> misleading... maybe "Total Sequences Assigned to Greengenes OTUs" (perhaps
> including the Greengenes version) would be more explicit?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/144#issuecomment-14201316
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by adamrp** [comment]
"Greengenes OTU Hits"?

**Comment by douginator2000** [comment]
Sounds good to me. Others?

On Wednesday, February 27, 2013, adamrp wrote:

> "Greengenes OTU Hits"?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/144#issuecomment-14210197
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
:+1:

**Comment by adamrp** [comment]
Looks like @douginator2000 fixed this, thanks!
