### ISSUE TITLE
Portal/welcome page needs content

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#162]
When logging in, you're greeted with a thin bar that just says "welcome". We should put some content here - not sure what, but something to help the user get started. Instructions on adding participants? Other information?

**Comment by adamrp** [comment]
Instructions for adding participants makes sense to me.  The first thing they should see, however, is probably the instructions about entering email-delivered kit verification codes, which WERE NOT in the mailed instructions.  Speaking of which, we need to generate that validation-code-entry page.

**Comment by ElDeveloper** [comment]
> Instructions on adding participants?

:+1:

---

Is the video with instructions on how to sample yourself available? Linking to this video would also be useful.

**Comment by megalodonatron** [comment]
I'll work on this.

**Comment by megalodonatron** [comment]
Should be fixed in latest pull req
