### ISSUE TITLE
test the site on internet explorer, windows

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#170]
sorry, whomever gets this

**Comment by megalodonatron** [comment]
-1 barf

**Comment by douginator2000** [comment]
LOL I actually have Win8 so I can do it. I'm probably the only one that
actually still likes Winders. :D It's the 15 years of Windows development I
did.

On Mon, Mar 18, 2013 at 10:08 AM, Meg Pirrung notifications@github.comwrote:

> -1 barf
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/170#issuecomment-15063760
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
it's all yours!

**Comment by douginator2000** [comment]
Site works. Only issues are: 

boxes around some icons (border not set perhaps?)

Kit ID/Password fields are of different sizes

Border around "Add new participants"

![Screen Shot 2013-03-18 at 12 15 48 PM](https://f.cloud.github.com/assets/608209/272058/40629632-8ff8-11e2-8a33-4630aa4b50b5.png)
![Screen Shot 2013-03-18 at 12 15 42 PM](https://f.cloud.github.com/assets/608209/272059/4070ebe2-8ff8-11e2-97b7-600f7408e6f1.png)
![Screen Shot 2013-03-18 at 12 15 25 PM](https://f.cloud.github.com/assets/608209/272060/40735a80-8ff8-11e2-832f-cab44332e71b.png)
![Screen Shot 2013-03-18 at 12 15 23 PM](https://f.cloud.github.com/assets/608209/272061/40794d8c-8ff8-11e2-9d42-552a84c67129.png)

**Comment by megalodonatron** [comment]
Recent css changes should have fixed these IE issues, can you check again Doug?

**Comment by douginator2000** [comment]
It looks pretty good. One oddity is that when logging a sample, selecting a sample date brings the control up over and over again. I.e. if I pick a date, normally the control would go away. It just reappears every time I make a selection.

**Comment by megalodonatron** [comment]
Only happens in IE?

**Comment by douginator2000** [comment]
Yes only IE, Chrome on Windows is fine.

**Comment by ElDeveloper** [comment]
Ok, this has been tested and the result of this is #546 and #594, I'll close this issue in favor of those other two.

**Comment by adamrp** [comment]
Thanks!
