### ISSUE TITLE
popup text on verification.psp needs to be filled in

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#176]
The question mark popup help needs to be added for this text:

Please verify that the barcode(s) you received in the mail match the barcode(s) here (?)

Currently it 404s

**Comment by adamrp** [comment]
Actually, we need a page barcode_popup.psp that will show the user an image of the barcode so that they know what to look for.

**Comment by megalodonatron** [comment]
did this in latest pull req

**Comment by megalodonatron** [comment]
:rabbit:
