### ISSUE TITLE
juvenile users with deceased parents can currently add samples

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#185]
Is this okay?  Or do we need the special consent forms before we allow them to add samples?

**Comment by megalodonatron** [comment]
Need to ask Gail if it's okay for them to continue or if they should be stopped until they provide proof of deceased parents.

**Comment by adamrp** [comment]
Gail says that we should not let them fill out the form.  I'll modify the code so that bruce waynes are stopped before entering the survey, emailed, and informed that they will hear from us.

**Comment by adamrp** [comment]
Right now, I'm just kicking them back to portal (without adding the participant) with the message that they'll hear from us.  Is it possible to add the participant if he/she has not filled out the survey?

**Comment by megalodonatron** [comment]
No, you can't add a participant unless you fill out the survey. When we have them come back we can just tell them not to check the deceased parent thing, or we can add some sort of logic to skip the consent and go straight to survey once they've given us proof.

**Comment by adamrp** [comment]
Okay, then my solution will work for the time being.  I think the right thing to do will be to add logic as you suggest so that the user can skip the consent form (after all, they've already filled it out once).  I'll add an issue for that, but we can take care of it later.

**Comment by douginator2000** [comment]
The consent is per-participant so it needs to always be there ya?

On Tue, Mar 19, 2013 at 3:49 PM, adamrp notifications@github.com wrote:

> Okay, then my solution will work for the time being. I think the right
> thing to do will be to add logic as you suggest so that the user can skip
> the consent form (after all, they've already filled it out once). I'll add
> an issue for that, but we can take care of it later.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/185#issuecomment-15145552
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
Except with the Bruce Waynes if they get to the point where we get emailed then they've already checked that they've read the consent. We can add a participant for them once we get the proof or whatever.

**Comment by adamrp** [comment]
But even after we add a participant for them, they still have to fill out the survey.  How can they do that?

**Comment by adamrp** [comment]
Meg and I discussed.  I think we need a column in ag_human_survey for "survey_complete" (y/n).  That way we can add a juvenile participant who has deceased parents and add logic so that they can bypass the consent form and proceed directly to the survey.  Note that this change will require changes to logic in other parts of the site as well!

**Comment by rob-knight** [comment]
Don't they instead have a guardian who needs to sign in loco parentis?

On Mar 19, 2013, at 4:47 PM, "adamrp" <notifications@github.com<mailto:notifications@github.com>> wrote:

Meg and I discussed. I think we need a column in ag_human_survey for "survey_complete" (y/n). That way we can add a juvenile participant who has deceased parents and add logic so that they can bypass the consent form and proceed directly to the survey. Note that this change will require changes to logic in other parts of the site as well!

**Comment by adamrp** [comment]
Pull req was merged that addresses this issue
