### ISSUE TITLE
Use 2 or 3 significant digits for height and weight on survey

### ISSUE THREAD

**Issue by wasade** [qiime/qiime_web_app#188]
It will reduce the weird rounding errors you get when you tab between boxes

**Comment by megalodonatron** [comment]
Did this in JS, limiting to 2 decimals, but it doesn't help the changing every time you tab issue.

**Comment by adamrp** [comment]
In JS, is it possible to store a more precise value (i.e., to 10 decimal places), but only display 2 of them?  If I am understanding the problem correctly, that would probably resolve the issue.

**Comment by megalodonatron** [comment]
same as #220
