### ISSUE TITLE
Travel to field on survey under general information

### ISSUE THREAD

**Issue by wasade** [qiime/qiime_web_app#189]
Could this be made a country pull down instead of free text?

**Comment by megalodonatron** [comment]
This was discussed but since the ability to add arbitrary fields is done with JS html injection, and populating the select is done in mod_python, it's not possible to inject the mod_python with js and have it interpreted.

**Comment by wasade** [comment]
But earlier in the questionnaire there is a pull down to select a country
of residence?

On Mar 18, 2013, at 14:28, Meg Pirrung notifications@github.com wrote:

This was discussed but since the ability to add arbitrary fields is done
with JS html injection, and populating the select is done in mod_python,
it's not possible to inject the mod_python with js and have it interpreted.

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/189#issuecomment-15079561
.

**Comment by megalodonatron** [comment]
Yep, but that one is populated on first view of the page. With the travel location fields they are injected after the page is already written so mod_python doesn't get run again.

**Comment by wasade** [comment]
Ah, kk

On Mar 18, 2013, at 14:31, Meg Pirrung notifications@github.com wrote:

Yep, but that one is populated on first view of the page. With the travel
location fields they are injected after the page is already written so
mod_python doesn't get run again.

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/189#issuecomment-15079750
.

**Comment by douginator2000** [comment]
It could still be done pretty easily: on that page, have python write out a
JS array that lists all of the countries. This array can then be assigned
to any dynamically added dropdown list because it'd always be on the page.

On Mon, Mar 18, 2013 at 2:32 PM, Daniel McDonald
notifications@github.comwrote:

> Ah, kk
> 
> On Mar 18, 2013, at 14:31, Meg Pirrung notifications@github.com wrote:
> 
> Yep, but that one is populated on first view of the page. With the travel
> location fields they are injected after the page is already written so
> mod_python doesn't get run again.
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/qiime/qiime_web_app/issues/189#issuecomment-15079750>
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/189#issuecomment-15079776
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
fixed in latest pull req
