### ISSUE TITLE
make sure all inline sql is translated to stored procedure before live launch.

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#191]
Very important to prevent sql injection attacks.

**Comment by ElDeveloper** [comment]
I'm going to start tackling this one from the SQL side of things, will wait until @douginator2000 gives me a heads up.

**Comment by ElDeveloper** [comment]
So far these are done:
- [x] `AGDataAccess.deleteAGGeneralValues()`
- [x] `AGDataAccess.addAGGeneralValue()`

After talking to @douginator2000 we agreed we would hold off on these:
- [ ] `AGDataAccess.insertAGMultiple()`
- [ ] `AGDataAccess.deleteAGMultiple()`

**Comment by douginator2000** [comment]
Vulnerable code covered.

**Comment by ElDeveloper** [comment]
![up-5](http://www.maniacworld.com/internet-high-five.jpg)
