### ISSUE TITLE
Index needs to somehow rerout to portal if you're already logged in

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#202]

**Comment by ElDeveloper** [comment]
I will take this one.

**Comment by douginator2000** [comment]
Thanks sir!

On Mon, Mar 18, 2013 at 8:35 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> I will take this one.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/202#issuecomment-15094366
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu
