### ISSUE TITLE
add delete functionality for participants and samples

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#203]
also possibly add a sample/participant overview page, where you can see which samples you've added to a participant, and what info you added to a sample

**Comment by megalodonatron** [comment]
Doug will add delete functionality

**Comment by megalodonatron** [comment]
I will do participant/sample overview pages if people think that is needed

**Comment by ElDeveloper** [comment]
Ok, this one has been assigned to @douginator2000.

**Comment by megalodonatron** [comment]
Overview templates currently look like:
![Screen Shot 2013-03-18 at 9 11 17 PM](https://f.cloud.github.com/assets/930642/273973/b479a2f0-9042-11e2-857b-c6f051058ee1.png)

![Screen Shot 2013-03-18 at 9 09 23 PM](https://f.cloud.github.com/assets/930642/273972/8b64d34e-9042-11e2-8bff-4137eead2cd1.png)

Will need someone to add in queries that populate with the right info, @douginator2000 can attach delete functionality to the buttons with some sort of "are you sure" intermediate page where we ask them to type in their password again or something

**Comment by adamrp** [comment]
It's not really a "delete" so much as "remove from participant", right?  They can always reassign the sample to another (or the same) participant after "deleting" it?  Also, in the participant overview page, will the sample IDs be links sending you to the sample overview page?

**Comment by megalodonatron** [comment]
yes the sample ids on the participant page would link to sample overviews

**Comment by douginator2000** [comment]
fixed.
