### ISSUE TITLE
Intermediate "Thank you for completing the survey" page

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#211]
Notes from Hongwei:
(5) Lack of a survey finishing page. Just a little bit weird to come
back to the add participant page.

**Comment by megalodonatron** [comment]
I actually think this is already covered with the message variable, it should say something like:
             successfully added as a participant! If you have not "
            "already done so, please confirm your identity and kit barcodes. "
            "Then, you may assign samples to participants.

but this is not happening, and suggestions @adamrp @ElDeveloper ?

**Comment by adamrp** [comment]
Currently that email message is only sent when the user is a bruce wayne.
 Can probably be fixed by moving the message in submit_human_survey.psp
from line 74 to line 59, but I don't have time to test right now.

**Comment by adamrp** [comment]
Actually I just found 15 minutes, I'll get on this.
