### ISSUE TITLE
Switching between fields for height and weight changes constantly

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#220]
Switching between the height and weight fields using the tab key, will constantly change the values that you've inputed.

**Comment by wasade** [comment]
related to #188

**Comment by wasade** [comment]
In the [conversion methods](https://github.com/qiime/qiime_web_app/blob/master/www/americangut/js/american_gut.js#L359), what about something like:

``` javascript
var cur_cm = document.getElementById('height_cm').value
if(!validateNumber(cur_cm)) { /* update if there isn't a value */
    document.getElementById('height_cm').value = centimeters.toFixed(2)
} else if(abs(centimeters - cur_cm) > 0.1) { /* update if the value is reasonably changed */
    document.getElementById('height_cm').value = centimeters.toFixed(2)
} else {}
```

**Comment by megalodonatron** [comment]
I'm fine with any solution proposed, can you make that change?

**Comment by wasade** [comment]
Don't have vm setup yet so cannot test

On Mar 19, 2013, at 12:21, Meg Pirrung notifications@github.com wrote:

I'm fine with any solution proposed, can you make that change?

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/220#issuecomment-15133465
.

**Comment by megalodonatron** [comment]
Okay I'll fix it
