### ISSUE TITLE
participant name and ag_login_id are not sufficient to identify a participant uniquely

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#221]
On submit_human_survey.psp, if the user is a bruce wayne, it identifies the user in the email that is sent to us by the participant_name and ag_login_id.  However, a single ag_login_id can have multiple participants with identical participant_names.

**Comment by adamrp** [comment]
Should we prevent the addition of two participants with identical names to the same ag_login_id?

**Comment by wasade** [comment]
what about jr. and sr.?

**Comment by adamrp** [comment]
I guess they would actually add jr. and sr. in their participant names when they take the survey.  The problem is that we probably dont want to list in the menu (on the left) two identically named participants.  Not only is this confusing for us (when the user has to contact us), but also confusing for the user.

**Comment by wasade** [comment]
makes sense
