### ISSUE TITLE
Add code to remove processed directories when deleting processing job

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#23]
Currently, removing a processing job does not clear the processed folders in the filesystem. Add code to make this happen.

**Comment by wasade** [comment]
this is very important

**Comment by ElDeveloper** [comment]
If I'm correct, this was resolved in pull request https://github.com/qiime/qiime_web_app/pull/63

@douginator2000 can you confirm this? :panda_face:

**Comment by douginator2000** [comment]
Yes this was resolved a while ago. Closing...
