### ISSUE TITLE
Firefox 19.0.2 -- Weird behavior for height and weight

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#252]
Trying to enter a value in `cm` first will behave oddly and set as NaN the `in` field.

The text entries become pseudo-non-editable, i. e. you cannot delete a single character.

---

Same thing happens for `kg` and `lb` pair of text entries.

**Comment by megalodonatron** [comment]
Works as expected for me in firefox and safari, though not that same version of firefox.

**Comment by ElDeveloper** [comment]
This has been fixed.
