### ISSUE TITLE
Error going from dietary questions to optional questions

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#255]
Uncaught SyntaxError: Unexpected token : 

This breaks the jquery on the optional questions page

**Comment by douginator2000** [comment]
Which optional questions did you add?

**Comment by megalodonatron** [comment]
All and none, it always happens

**Comment by douginator2000** [comment]
Can't get anything to show up in Chrome...

**Comment by megalodonatron** [comment]
:rabbit:
