### ISSUE TITLE
Weird message in page 4 in survey -- Firefox

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#257]
Page 4 shows a weird message when trying to hit continue:

![Captura de pantalla 2013-03-20 a la s 00 55 06](https://f.cloud.github.com/assets/375307/279511/2bc46028-912b-11e2-989a-c19cd2992ec6.png)

@douginator2000 confirmed the same problem.

**Comment by douginator2000** [comment]
Also have this in IE on Windows
![Screen Shot 2013-03-20 at 1 07 48 AM](https://f.cloud.github.com/assets/608209/279536/063e244a-912d-11e2-9d51-984d1da1140d.png)

**Comment by douginator2000** [comment]
Suspect there is some coding difference on just this page?

**Comment by ElDeveloper** [comment]
This was closed by @meganap.
