### ISSUE TITLE
In Internet Explorer, clicking any + to add fields causes leave/stay dialog to appear

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#259]
As title says. Might have to just remove this code.

![Screen Shot 2013-03-20 at 1 10 38 AM](https://f.cloud.github.com/assets/608209/279543/8f3fb984-912d-11e2-93ac-bf07fbd4ffe5.png)

**Comment by megalodonatron** [comment]
fixed by removing those messages for now
