### ISSUE TITLE
In IE, percent up/down controls do not appear

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#261]
Instead an X shows up, and NaN appears if you don't enter it all (see screenshot)

![Screen Shot 2013-03-20 at 1 19 13 AM](https://f.cloud.github.com/assets/608209/279562/9d9ff09c-912e-11e2-9128-e988835b6d47.png)

**Comment by megalodonatron** [comment]
fixed NaN issue, up/down arrows are IE not rendering html things, can't fix
