### ISSUE TITLE
Something wrong with consent form emailing

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#283]
I've gotten a lot of emails from people saying the consent form didn't email, maybe this is a systematic issue? Should check it out.

**Comment by ElDeveloper** [comment]
Hmm could this be the e-mail going to their spam folder or could this be something else? I'm will do some tests. Also this is related to #278.

**Comment by megalodonatron** [comment]
It's not that they're not getting the email, it's that they're getting the "there was a problem sending your consent form please contact us immediately" message as soon as they finish the survey

**Comment by megalodonatron** [comment]
Though I suppose they probably aren't getting the email either

**Comment by ElDeveloper** [comment]
Oh, I guess what you mention about this being a systematic issue makes more sense. Just tried adding a participant and I got a consent form emailed, it didn't show up in the spam box so that's also good.

I assume this might have something to do with the email server? I cannot think of something else that might be causing this. Or maybe some crazy characters in their names/emails?

**Comment by megalodonatron** [comment]
I think the people's info still gets added even if they do get that message, so maybe we can check the database for their emails or something.

**Comment by douginator2000** [comment]
Sounds like we should add a bunch of error trapping on the last page to a)
capture the form field values so they're not lost, b) log any emailing
issues, and c) let the user know what the should do (if we don't already
have something like this).

On Sat, Mar 23, 2013 at 10:48 AM, Meg Pirrung notifications@github.comwrote:

> I think the people's info still gets added even if they do get that
> message, so maybe we can check the database for their emails or something.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/283#issuecomment-15340241
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by wasade** [comment]
Should be able to check the mail logs on www, but need to be root. Should
be under /var/log/exim. Will try and take a peek this morning to see what's
up. Do we know what type of exception??

On Mar 23, 2013, at 10:24, Doug Wendel notifications@github.com wrote:

Sounds like we should add a bunch of error trapping on the last page to a)
capture the form field values so they're not lost, b) log any emailing
issues, and c) let the user know what the should do (if we don't already
have something like this).

On Sat, Mar 23, 2013 at 10:48 AM, Meg Pirrung notifications@github.comwrote:

> I think the people's info still gets added even if they do get that
> message, so maybe we can check the database for their emails or
> something.
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/qiime/qiime_web_app/issues/283#issuecomment-15340241>
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/283#issuecomment-15340853
.

**Comment by megalodonatron** [comment]
There's one email where someone actually got an exception, but the rest of the people just say that they got the "couldnt send consent form" message. I'm not sure if those two are even the same issue.

**Comment by megalodonatron** [comment]
Here's the issue the one guy sent:
MOD_PYTHON ERROR

ProcessId:      10329
Interpreter:    'www.microbio.me'

ServerName:     'www.microbio.me'
DocumentRoot:   '/var/wwwroot/htdocs'

URI:            '/AmericanGut/submit_human_survey.psp'
Location:       None
Directory:      '/var/wwwroot/htdocs/AmericanGut/'
Filename:       '/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp'
PathInfo:       ''

Phase:          'PythonHandler'
Handler:        'mod_python.psp'

Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1537, in HandlerDispatch
    default=default_handler, arg=req, silent=hlist.silent)

  File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1229, in _process_target
    result = _execute_target(config, req, object, arg)

  File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1128, in _execute_target
    result = object(arg)

  File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 337, in handler
    p.run()

  File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 243, in run
    exec code in global_scope

  File "/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp", line 130, in <module>
    ag_data_access.addAGHumanParticipant(ag_login_id, form['participant_name'])

  File "/home/wwwuser/git/qiime_web_app/python_code/data_access/ag_data_access.py", line 90, in addAGHumanParticipant
    con.cursor().callproc('ag_add_participant', [ag_login_id, participant_name])

IntegrityError: ORA-02291: integrity constraint (QIIME_METADATA.FK_AG_HUM_SURV_TO_AG_LOGIN) violated - parent key not found
ORA-06512: at "QIIME_METADATA.AG_ADD_PARTICIPANT", line 9
ORA-06512: at line 1

**Comment by wasade** [comment]
That last one is db issue. On the blanket exception catch when emailing, is
it printing or storing the associated e.msg()?

On Mar 23, 2013, at 10:36, Meg Pirrung notifications@github.com wrote:

Here's the issue the one guy sent:
MOD_PYTHON ERROR

ProcessId: 10329
Interpreter: 'www.microbio.me'

ServerName: 'www.microbio.me'
DocumentRoot: '/var/wwwroot/htdocs'

URI: '/AmericanGut/submit_human_survey.psp'
Location: None
Directory: '/var/wwwroot/htdocs/AmericanGut/'
Filename: '/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp'
PathInfo: ''

Phase: 'PythonHandler'
Handler: 'mod_python.psp'

Traceback (most recent call last):

File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1537,
in HandlerDispatch
default=default_handler, arg=req, silent=hlist.silent)

File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1229,
in _process_target
result = _execute_target(config, req, object, arg)

File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1128,
in _execute_target
result = object(arg)

File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 337, in
handler
p.run()

File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 243, in run
exec code in global_scope

File "/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp", line 130,
in
ag_data_access.addAGHumanParticipant(ag_login_id, form['participant_name'])

File
"/home/wwwuser/git/qiime_web_app/python_code/data_access/ag_data_access.py",
line 90, in addAGHumanParticipant
con.cursor().callproc('ag_add_participant', [ag_login_id, participant_name])

IntegrityError: ORA-02291: integrity constraint
(QIIME_METADATA.FK_AG_HUM_SURV_TO_AG_LOGIN) violated - parent key not found
ORA-06512: at "QIIME_METADATA.AG_ADD_PARTICIPANT", line 9
ORA-06512: at line 1

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341096
.

**Comment by megalodonatron** [comment]
I'm not sure if that error sends anything anywhere else, 
do you know @adamrp ?

**Comment by douginator2000** [comment]
Yeah that's a foreign key issue that basically says the ag_login_id (set in
the session when you log in) was no longer valid or no longer existed in
the ag_login table when they submitted their survey. Could be that the
browser dropped the session or something else bizarre happened.

On Sat, Mar 23, 2013 at 11:44 AM, Meg Pirrung notifications@github.comwrote:

> I'm not sure if that error sends anything anywhere else,
> do you know @adamrp https://github.com/adamrp ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341259
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by wasade** [comment]
Maybe the user left their browser open for a while and then came back to it?

On Mar 23, 2013, at 11:00, Doug Wendel notifications@github.com wrote:

Yeah that's a foreign key issue that basically says the ag_login_id (set in
the session when you log in) was no longer valid or no longer existed in
the ag_login table when they submitted their survey. Could be that the
browser dropped the session or something else bizarre happened.

On Sat, Mar 23, 2013 at 11:44 AM, Meg Pirrung notifications@github.comwrote:

> I'm not sure if that error sends anything anywhere else,
> do you know @adamrp https://github.com/adamrp ?
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341259>
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341529
.

**Comment by douginator2000** [comment]
It's possible though the session timeout is very long - like a week?

On Sat, Mar 23, 2013 at 12:46 PM, Daniel McDonald
notifications@github.comwrote:

> Maybe the user left their browser open for a while and then came back to
> it?
> 
> On Mar 23, 2013, at 11:00, Doug Wendel notifications@github.com wrote:
> 
> Yeah that's a foreign key issue that basically says the ag_login_id (set
> in
> the session when you log in) was no longer valid or no longer existed in
> the ag_login table when they submitted their survey. Could be that the
> browser dropped the session or something else bizarre happened.
> 
> On Sat, Mar 23, 2013 at 11:44 AM, Meg Pirrung notifications@github.comwrote:
> 
> > I'm not sure if that error sends anything anywhere else,
> > do you know @adamrp https://github.com/adamrp ?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341259>
> > .
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edu
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341529>
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/283#issuecomment-15342392
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by wasade** [comment]
Weird security settings?

On Mar 24, 2013, at 9:46, Doug Wendel notifications@github.com wrote:

It's possible though the session timeout is very long - like a week?

On Sat, Mar 23, 2013 at 12:46 PM, Daniel McDonald
notifications@github.comwrote:

> Maybe the user left their browser open for a while and then came back to
> it?
> 
> On Mar 23, 2013, at 11:00, Doug Wendel notifications@github.com wrote:
> 
> Yeah that's a foreign key issue that basically says the ag_login_id (set
> in
> the session when you log in) was no longer valid or no longer existed in
> the ag_login table when they submitted their survey. Could be that the
> browser dropped the session or something else bizarre happened.
> 
> On Sat, Mar 23, 2013 at 11:44 AM, Meg Pirrung notifications@github.comwrote:
> 
> > I'm not sure if that error sends anything anywhere else,
> > do you know @adamrp https://github.com/adamrp ?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341259>
> > .
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edu
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/qiime/qiime_web_app/issues/283#issuecomment-15341529>
> .
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/qiime/qiime_web_app/issues/283#issuecomment-15342392>
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/283#issuecomment-15362387
.

**Comment by adamrp** [comment]
Sorry, didn't see this.  I just tested with a bad email address (i entered 'notanaddress' into the text box), and I got the error message.  I assume if we check on those people who did not receive the form correctly (in the AG_HUMAN_SURVEY table), we will see a malformed email address.

I do not think we are storing the exception text anywhere

**Comment by ElDeveloper** [comment]
Would it be fine to add a log file that stored the information for failed e-mails? Or should this take a different approach.

If so, I think the easiest is to use the logging module and have it store things in `/tmp/americangut_sad_users.log` or something like that hehe.

**Comment by adamrp** [comment]
Makes sense to me!  I think we should also write some code that pulls the necessary variables from the DB (from ag_human_survey) and generates a new consent form, which we can email to people manually.  Most of this code probably already exists, but we should move it into a module that we can easily access when someone contacts us about a failed-to-send consent form
