### ISSUE TITLE
Error that guy emailed to us

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#284]
MOD_PYTHON ERROR

ProcessId: 10329
Interpreter: 'www.microbio.me'

ServerName: 'www.microbio.me'
DocumentRoot: '/var/wwwroot/htdocs'

URI: '/AmericanGut/submit_human_survey.psp'
Location: None
Directory: '/var/wwwroot/htdocs/AmericanGut/'
Filename: '/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp'
PathInfo: ''

Phase: 'PythonHandler'
Handler: 'mod_python.psp'

Traceback (most recent call last):

File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1537, in HandlerDispatch
default=default_handler, arg=req, silent=hlist.silent)

File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1229, in _process_target
result = _execute_target(config, req, object, arg)

File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1128, in _execute_target
result = object(arg)

File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 337, in handler
p.run()

File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 243, in run
exec code in global_scope

File "/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp", line 130, in 
ag_data_access.addAGHumanParticipant(ag_login_id, form['participant_name'])

File "/home/wwwuser/git/qiime_web_app/python_code/data_access/ag_data_access.py", line 90, in addAGHumanParticipant
con.cursor().callproc('ag_add_participant', [ag_login_id, participant_name])

IntegrityError: ORA-02291: integrity constraint (QIIME_METADATA.FK_AG_HUM_SURV_TO_AG_LOGIN) violated - parent key not found
ORA-06512: at "QIIME_METADATA.AG_ADD_PARTICIPANT", line 9
ORA-06512: at line 1

**Comment by douginator2000** [comment]
That's pretty odd - means that the ag_login_id which the procedure
attempted to insert into the ag_human_survey table no longer existed in the
ag_login_table. Session variable corrupted? Data changed? Don't know - this
is the only one we've gotten that matches this error signature?

On Sat, Mar 23, 2013 at 11:46 AM, Meg Pirrung notifications@github.comwrote:

> MOD_PYTHON ERROR
> 
> ProcessId: 10329
> Interpreter: 'www.microbio.me'
> 
> ServerName: 'www.microbio.me'
> DocumentRoot: '/var/wwwroot/htdocs'
> 
> URI: '/AmericanGut/submit_human_survey.psp'
> Location: None
> Directory: '/var/wwwroot/htdocs/AmericanGut/'
> Filename: '/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp'
> PathInfo: ''
> 
> Phase: 'PythonHandler'
> Handler: 'mod_python.psp'
> 
> Traceback (most recent call last):
> 
> File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1537,
> in HandlerDispatch
> default=default_handler, arg=req, silent=hlist.silent)
> 
> File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1229,
> in _process_target
> result = _execute_target(config, req, object, arg)
> 
> File "/usr/lib/python2.6/site-packages/mod_python/importer.py", line 1128,
> in _execute_target
> result = object(arg)
> 
> File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 337, in
> handler
> p.run()
> 
> File "/usr/lib/python2.6/site-packages/mod_python/psp.py", line 243, in run
> exec code in global_scope
> 
> File "/var/wwwroot/htdocs/AmericanGut/submit_human_survey.psp", line 130,
> in
> ag_data_access.addAGHumanParticipant(ag_login_id, form['participant_name'])
> 
> File
> "/home/wwwuser/git/qiime_web_app/python_code/data_access/ag_data_access.py",
> line 90, in addAGHumanParticipant
> con.cursor().callproc('ag_add_participant', [ag_login_id,
> participant_name])
> 
> IntegrityError: ORA-02291: integrity constraint
> (QIIME_METADATA.FK_AG_HUM_SURV_TO_AG_LOGIN) violated - parent key not found
> ORA-06512: at "QIIME_METADATA.AG_ADD_PARTICIPANT", line 9
> ORA-06512: at line 1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/284
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
Yes, he is the only one who has sent this message, I just had no idea what to tell him about it.

**Comment by douginator2000** [comment]
Was he able to resubmit and enter his data?

On Sat, Mar 23, 2013 at 11:54 AM, Meg Pirrung notifications@github.comwrote:

> Yes, he is the only one who has sent this message, I just had no idea what
> to tell him about it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/284#issuecomment-15341426
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu
