### ISSUE TITLE
Add ability to delete prior meta-analyses 

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#29]
There's currently no way to remove these. List gets very cluttered - add way to delete.

**Comment by wasade** [comment]
just within your own user, correct?

**Comment by douginator2000** [comment]
Yes, as it stands, you can only see your own analyses anyway, so adding a
delete will be safe.

On Tue, Oct 23, 2012 at 9:56 AM, Daniel McDonald
notifications@github.comwrote:

> just within your own user, correct?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/29#issuecomment-9707303.

## 

Doug Wendel, PRA
University of Colorado at Boulder
Department of Chemistry and Biochemistry
Knight Lab

**Comment by ackermag** [comment]
I thought we fixed this?  There is a delete button on the meta-analysis page

**Comment by douginator2000** [comment]
You are correct Gail, had forgotten that went in. Excellent! Closing.
