### ISSUE TITLE
Barcode scanner utility

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#298]
Need to check that sample has been applied, shows green screen or red screen depending on whether or not they can continue with the sample

To continue the person must have signed the consent form, filled out the survey and applied the sample being processed.

**Comment by megalodonatron** [comment]
green = sample has been applied which inherently means consent has been given and survey has been filled out
red = sample not applied

**Comment by megalodonatron** [comment]
yellow = barcode has been scanned, we have already sent a follow-up email within the past (amount of time)

need to deal with if the person replies to our auto-email but is still not filling out their form, but has made contact

**Comment by megalodonatron** [comment]
Currently checked in is barcode_util.psp in wwwadmin
There are some templated-out if statements that look like:

```
<%
verified = True
if verified:

%>
```

and need to wrap those ifs around the different html elements that already exist in that file(green, yellow, red) with a real check for verification from the DB.

Need columns in the DB for whether or not the whole thing (consent, survey, sample applied) is verified and a column for the last time a reminder email was sent if the person wasn't verified.

**Comment by megalodonatron** [comment]
Would also be nice to use this as a way to know when samples are received, then on the main AG website under sample we can have a check box for sample received.

**Comment by megalodonatron** [comment]
Template page located in barcode_util.psp added when moved to git 3301de84c5f367f5d5d0aecf518a32226b7dca89

**Comment by douginator2000** [comment]
Sorry for the delay Meg, the barcode SQL and ag_data_access function
are checked in. The only thing you'll need to call is checkBarcode()
in ag_data_access.

E.g.

ag_data_access.checkBarcode('000004356')

The return type is a list. If the list is empty, nothing was found
(i.e. the sample has not yet been logged). If there's an item, it's a
tuple of values.

Some test code if you want to verify the function:

from data_access_connections import data_access_factory
from enums import *
ag_data_access = data_access_factory(ServerConfig.data_access_type,
'american_gut')
ag_data_access.checkBarcode('')
ag_data_access.checkBarcode('000003567')

**Comment by megalodonatron** [comment]
Sweet, I'll check this out and try to get everything hooked up

**Comment by douginator2000** [comment]
Sounds great! Let me know if you need anything else.

On Thu, May 16, 2013 at 1:16 PM, Meg Pirrung notifications@github.comwrote:

> Sweet, I'll check this out and try to get everything hooked up
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/298#issuecomment-18022838
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by douginator2000** [comment]
One update: When we scan a barcode and everything is OK, update the database to reflect receipt of sample tube. Also make this obvious to the user: likely email them at the provided login email addy and update the UI so that it's obvious it's been received and also prevent deletion of the sample/survey on the website for users.

**Comment by wasade** [comment]
ETA?

**Comment by megalodonatron** [comment]
### Barcode util basic functionality now implemented

It can tell if the barcode is from a kit that is:
- completely unverified
- verified but not assigned
- verified and assigned

### What we still need:

Email functionality, do we want:
- auto email
- link to click to email people

We need a date of last email at the very least

To let users know that their sample has been received:
- on a verified and assigned result we need to update something in the database that marks that barcode as received
- also need to be able to query the db for barcode received

Then on the user facing site when you click on the barcode there will be a checkbox for "received" and portal will say something about that barcode being received.

**Comment by douginator2000** [comment]
Enhancement: In the case where the kit has only one barcode and the user has a) filled out their survey, but b) has not filled out the sample details: When barcode is scanned then pop up the sample details form so that whoever scans it (Kris, others?) can directly enter sample data if it happens to be entered on the tube.

**Comment by douginator2000** [comment]
Lots of additional enhancements:
- When scanning, display all entered metadata (sample details, survey, etc..). Will help troubleshoot strange data (e.g. oddball birth dates, etc...)
- If no sample details are logged for sample, present form to manually enter sample details from tube. This still isn't enough information to use the sample, but it provides a mechanism for recording what we can.
- When scanning, if it's a human survey and survey/sample details aren't present, add button that allows an email to be sent to remind user to fill out online details:
  - include login details for their account (send kit_id, password, verification)
  - Clickable address for website
  - Clear instructions on what to do specifically (e.g. add participant, add sample info)
- Change user interface on participant portal to show participant that sample has been received (Doug will deploy shortly)
- Update database when sample is scanned to flag as received (Doug will deploy shortly)
- Add new fields to track the visible status of the sample when received. Some suggestions are:
  moldy? (checkbox)
  other? (checkboxes/radio/dropdown lists - stuff we can use in analysis or to troubleshoot)
  Notes field for sample receiver to enter other details

**Comment by douginator2000** [comment]
Just to make sure this makes it in, we should send an automatic email to participants letting them know the sample was received.

**Comment by RNAer** [comment]
there are two ways to do this. 1) send an email saying "we receive the
sample with barcode xxxxxxxxx blabla" whenever the sample arrives; 2) or
send the email once we receive all the samples from the participants. which
one is better? open for discussion

**Comment by douginator2000** [comment]
2 new fields added to support new additional functionality:

sample_postmark_date: Added to barcode table. This should be set to the postmark date on the envelope if it can be read/exists

scan_date: Added to barcode table. This should be set to the date the sample tube is scanned by us.

**Comment by RNAer** [comment]
+1

**Comment by ElDeveloper** [comment]
I like the idea of having an e-mail per sample, the problem with the e-mail per kit is that the times at which swabs arrive for some swab-sets is variable as users find themselves trying to track pre-post microbiota states to medical interventions or general traveling.

**Comment by RNAer** [comment]
I agree. it makes code simpler too. we decided to go with that.

**Comment by douginator2000** [comment]
+1

On Wed, Jun 26, 2013 at 3:50 PM, Zech Xu notifications@github.com wrote:

> I agree. it makes code simpler too. we decided to go with that.
> 
> On Wed, Jun 26, 2013 at 3:45 PM, Yoshiki Vázquez Baeza <
> notifications@github.com> wrote:
> 
> > I like the idea of having an e-mail per sample, the problem with the
> > e-mail per kit is that the times at which swabs arrive for some
> > swab-sets
> > is variable as users find themselves trying to track pre-post microbiota
> > states to medical interventions or general traveling.
> > 
> > El 26/06/2013, a las 14:42, Zech Xu notifications@github.com
> > escribió:
> > 
> > > there are two ways to do this. 1) send an email saying "we receive the
> > > sample with barcode xxxxxxxxx blabla" whenever the sample arrives; 2)
> > > or
> > > send the email once we receive all the samples from the participants.
> > > which
> > > one is better? open for discussion
> > > 
> > > On Wed, Jun 26, 2013 at 2:35 PM, Doug Wendel notifications@github.comwrote:
> > > 
> > > > Just to make sure this makes it in, we should send an automatic
> > > > email
> > > > to
> > > > participants letting them know the sample was received.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/qiime/qiime_web_app/issues/298#issuecomment-20077959>
> > > > 
> > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/issues/298#issuecomment-20082526>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/298#issuecomment-20082835
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
Util exists so this thread should be closed and any issues with the barcode scanner util should be opened as new tickets.

**Comment by ElDeveloper** [comment]
Woww, that's an old issue, thanks for looking through these!
