### ISSUE TITLE
Add survey/add sample for environmental and other host associated

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#299]

**Comment by megalodonatron** [comment]
Need to be able to add samples that aren't attached to participants

**Comment by douginator2000** [comment]
I have most of the framework in place to handle this now. I'm including a screenshot of how this looks: left menu contains new items to add animal and general samples (feedback on the actual text for the menu items??). 

![Screen Shot 2013-04-01 at 3 22 16 PM](https://f.cloud.github.com/assets/608209/325676/4d33bd30-9b12-11e2-93c3-5cf067fb504f.png)

The code has been refactored such that each sample type is encoded in the form which the link submits. The add_sample.psp page is now just another fusebox-style page that includes the appropriate form type. 

We need to decide on field names first for the environmental samples. Thoughts on what we should collect? Here's a few items to start the list:
- What was sampled (this could be a list or we could open it up to the ENVO ontology, though this could quickly become confusing for the user and lead to more difficult downstream analysis for us.)
- Geolocation of the sample
- Sample date/time (we already have this)

Others?

**Comment by megalodonatron** [comment]
I think we should have environmental rather than general

**Comment by megalodonatron** [comment]
What terms do we need for environmental? Can we use a pared-down list of ENVO terms?

**Comment by douginator2000** [comment]
So as I mentioned earlier in this thread, if we can generate a list of commonly sampled environments, plus a "comments" field, we could probably map all 3 of the envo fields without having to have the user explicitly pick them (which would be pretty confusing for them).

So as a short list of fields:
- Environment Sampled (dropdown with enough coverage to capture most reasonable cases, and we can always add more to this list at any time)
- The same sample date/time we've been using
- Geolocation? Could just infer this from the participant's location
- Notes fields (allows them to type in additional stuff for the sample)

Thoughts?

**Comment by megalodonatron** [comment]
Yeah, maybe just indoor/outdoor, zipcode and then the notes field where they can type what exactly it was they sampled

**Comment by douginator2000** [comment]
We should provide a list of items so that we can map to envo types I think.

On Wednesday, April 3, 2013, Meg Pirrung wrote:

> Yeah, maybe just indoor/outdoor, zipcode and then the notes field where
> they can type what exactly it was they sampled
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/299#issuecomment-15867190
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
Email from Gail says:
Examples include:
water, soil, home surfaces, food

I wouldn't recommend sampling water without filtering a bunch of it and most home surfaces tend to be very low biomass and so are more likely to fail.

and then in another email:

soil, plants, foodstuff, surfaces, water, insects

**Comment by douginator2000** [comment]
That's a good start - maybe we should have a 5 minute meeting to produce a
more comprehensive list? Needs to be something that we can directly tie to
the 3 ENVO types but represent in a single text value.

Maybe this would be easier if we had a larger list to distill? Here are the
env_matter types we currently have in the database across all studies:

ENVO:Agricultural soil
ENVO:Animal-associated habitat
ENVO:Farm soil
ENVO:Surface
ENVO:Tropical and subtropical dry broadleaf forest biome
ENVO:Tropical soil
ENVO:Volcanic rock
ENVO:Water
ENVO:agricultural soil
ENVO:air
ENVO:alpine soil
ENVO:anaerobic digester sludge
ENVO:anaerobic sediment
ENVO:animal habitation
ENVO:animal litter
ENVO:animal manure
ENVO:animal-associated habitat
ENVO:anthropogenic feature
ENVO:beer
ENVO:biofilm
ENVO:blood plasma
ENVO:bodily fluid
ENVO:brackish water
ENVO:bulk soil
ENVO:carcass
ENVO:cell culture
ENVO:clay soil
ENVO:coastal water
ENVO:compost soil
ENVO:creek
ENVO:dust
ENVO:ear wax
ENVO:egg
ENVO:farm soil
ENVO:feces
ENVO:food
ENVO:forest soil
ENVO:fresh water
ENVO:fresh water aquarium
ENVO:grassland soil
ENVO:ground water
ENVO:gut
ENVO:human-associated habitat
ENVO:hypersaline water
ENVO:ice
ENVO:lake
ENVO:lake sediment
ENVO:lawn soil
ENVO:manured soil
ENVO:marine sediment
ENVO:meadow soil
ENVO:microbial mat
ENVO:mountain forest soil
ENVO:mouth
ENVO:mucus
ENVO:nesting material
ENVO:nitisol
ENVO:ocean water
ENVO:oil contaminated soil
ENVO:orchard soil
ENVO:organic material feature
ENVO:organism-associated habitat
ENVO:peat soil
ENVO:plant-associated habitat
ENVO:rhizosphere
ENVO:rock
ENVO:saline lake sediment
ENVO:saline water
ENVO:saliva
ENVO:sand
ENVO:sandstone
ENVO:seawater
ENVO:sebum
ENVO:sediment
ENVO:snow field
ENVO:soil
ENVO:spruce forest soil
ENVO:sterile water
ENVO:stream
ENVO:stream sediment
ENVO:surface
ENVO:sweat
ENVO:travertine
ENVO:urine
ENVO:vegetable garden soil
ENVO:water
ENVO:wine
ENVO:wood
EVNO:mucus

On Thu, Apr 4, 2013 at 11:13 AM, Meg Pirrung notifications@github.comwrote:

> Email from Gail says:
> Examples include:
> water, soil, home surfaces, food
> 
> I wouldn't recommend sampling water without filtering a bunch of it and
> most home surfaces tend to be very low biomass and so are more likely to
> fail.
> 
> and then in another email:
> 
> soil, plants, foodstuff, surfaces, water, insects
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/299#issuecomment-15910698
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by douginator2000** [comment]
Okay, Meg and I went over the list. Below is the very short list of terms
we came up with. In general, we removed all terms describing fluids because
they probably can't be reasonably sampled by the participants. Also, all
human and animal associated terms were removed since this should only be
for environmental samples. Further thoughts?

Animal Habitat
Biofilm
Dust
Food
Indoor Surface
Outdoor Surface
Plant habitat
Soil

On Thu, Apr 4, 2013 at 11:19 AM, Doug Wendel douginator2000@gmail.comwrote:

> That's a good start - maybe we should have a 5 minute meeting to produce a
> more comprehensive list? Needs to be something that we can directly tie to
> the 3 ENVO types but represent in a single text value.
> 
> Maybe this would be easier if we had a larger list to distill? Here are
> the env_matter types we currently have in the database across all studies:
> 
> ENVO:Agricultural soil
> ENVO:Animal-associated habitat
> ENVO:Farm soil
> ENVO:Surface
> ENVO:Tropical and subtropical dry broadleaf forest biome
> ENVO:Tropical soil
> ENVO:Volcanic rock
> ENVO:Water
> ENVO:agricultural soil
> ENVO:air
> ENVO:alpine soil
> ENVO:anaerobic digester sludge
> ENVO:anaerobic sediment
> ENVO:animal habitation
> ENVO:animal litter
> ENVO:animal manure
> ENVO:animal-associated habitat
> ENVO:anthropogenic feature
> ENVO:beer
> ENVO:biofilm
> ENVO:blood plasma
> ENVO:bodily fluid
> ENVO:brackish water
> ENVO:bulk soil
> ENVO:carcass
> ENVO:cell culture
> ENVO:clay soil
> ENVO:coastal water
> ENVO:compost soil
> ENVO:creek
> ENVO:dust
> ENVO:ear wax
> ENVO:egg
> ENVO:farm soil
> ENVO:feces
> ENVO:food
> ENVO:forest soil
> ENVO:fresh water
> ENVO:fresh water aquarium
> ENVO:grassland soil
> ENVO:ground water
> ENVO:gut
> ENVO:human-associated habitat
> ENVO:hypersaline water
> ENVO:ice
> ENVO:lake
> ENVO:lake sediment
> ENVO:lawn soil
> ENVO:manured soil
> ENVO:marine sediment
> ENVO:meadow soil
> ENVO:microbial mat
> ENVO:mountain forest soil
> ENVO:mouth
> ENVO:mucus
> ENVO:nesting material
> ENVO:nitisol
> ENVO:ocean water
> ENVO:oil contaminated soil
> ENVO:orchard soil
> ENVO:organic material feature
> ENVO:organism-associated habitat
> ENVO:peat soil
> ENVO:plant-associated habitat
> ENVO:rhizosphere
> ENVO:rock
> ENVO:saline lake sediment
> ENVO:saline water
> ENVO:saliva
> ENVO:sand
> ENVO:sandstone
> ENVO:seawater
> ENVO:sebum
> ENVO:sediment
> ENVO:snow field
> ENVO:soil
> ENVO:spruce forest soil
> ENVO:sterile water
> ENVO:stream
> ENVO:stream sediment
> ENVO:surface
> ENVO:sweat
> ENVO:travertine
> ENVO:urine
> ENVO:vegetable garden soil
> ENVO:water
> ENVO:wine
> ENVO:wood
> EVNO:mucus
> 
> On Thu, Apr 4, 2013 at 11:13 AM, Meg Pirrung notifications@github.comwrote:
> 
> > Email from Gail says:
> > Examples include:
> > water, soil, home surfaces, food
> > 
> > I wouldn't recommend sampling water without filtering a bunch of it and
> > most home surfaces tend to be very low biomass and so are more likely to
> > fail.
> > 
> > and then in another email:
> > 
> > soil, plants, foodstuff, surfaces, water, insects
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/299#issuecomment-15910698
> > .
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edu

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
:+1:

**Comment by megalodonatron** [comment]
Need to add fields for non-human host associated, I'll put the proposed fields in this issue.

**Comment by megalodonatron** [comment]
Survey Questions:

Type
- Dog
- Cat
- Small mammals (:rabbit:)
- Fish
- Bird
- Horse
- Goat
- Reptile
- Amphibian
- Other

Origin
- Breeder
- Pound
- Home
- Wild

Birth Date

Sex

Setting
- Urban
- Suburban
- Rural

Weight category
- Underweight
- Skinny
- Normal
- Chubby
- Overweight

Diet
- Pet store food
- Human food
- Wild food

Diet type
- Dry
- Wet
- Both

Diet special
- Organic
- Grain free

Social living status
- Lives alone with human(s)
- Lives alone no/limited humans (pound)
- Lives with other animals and humans (family pet with other pets)
- Lives with other animals/limited humans (farm animal)

List other pets and their type

List age/sex of humans

Time spent outside

Dog Optional Questions:

Toilet water access
- Regular
- Sometimes
- Never

Turd burglar
- High (anything in sight)
- Moderate (curious, occasional sample)
- Low (once or twice)
- Never

Sampling questions:

Site
- Stool
- Oral
- Skin (ears, nose, paw pads)
- Fur

Date
Time
Notes

**Comment by adamrp** [comment]
Looks pretty good to me, maybe change the category from "small mammal" to "other mammal" 
Also, diet type should include an option for wet+dry, since many pets eat both

**Comment by megalodonatron** [comment]
Maybe small mammals and large mammal? Or maybe herbivorous mammal vs carnivorous mammal? I don't really know what is going to be most telling for a microbiome study. I'll change the food stuff to include both wet & dry food.

**Comment by ElDeveloper** [comment]
:+1: looks good. I think that small mammal and large mammal should be sufficient.

**Comment by adamrp** [comment]
I think we can close this issue now.
