### ISSUE TITLE
Height and Weight fields accepting invalid characters?

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#301]
I've seen some entries in the AG_HUMAN_SURVEY table where HEIGHT_IN (which should be numerical) is:

5'10

Need code to disallow this kind of thing.

**Comment by wasade** [comment]
Isn't the schema defining these as ints or floats?

On Apr 2, 2013, at 11:45, adamrp notifications@github.com wrote:

I've seen some entries in the AG_HUMAN_SURVEY table where HEIGHT_IN (which
should be numerical) is:

5'10

Need code to disallow this kind of thing.

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/301
.

**Comment by megalodonatron** [comment]
And I have it set so that you should only be allowed to type numbers and nothing else, so if they're still managing to put weird chars in I don't know. I do use javascript for the validation though.

**Comment by adamrp** [comment]
I seem to recall that Form Autofill functions seems to be able to
circumvent some of those checks, although I'm not sure how many Form
Autofill things have a setting for Height...

**Comment by megalodonatron** [comment]
Yeah, I could see that. Copy/pasting isn't prevented either, so you can paste whatever into those fields. I'll add some validation for once the continue button is clicked.

**Comment by ElDeveloper** [comment]
Should be fixed by #307
