### ISSUE TITLE
check out fitday, add link to recommendation

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#303]
A nutritionist uses fitday and so does her school, and she recommended it as a much better option compared to caloriecount

Someone should check out the site and see if it will work for our purposes.

from the user:
"By the way, fit day.com is a much better food logging website - it gives you all macro and micronutrients, fiber, cholesterol."

**Comment by megalodonatron** [comment]
checking it out

**Comment by ElDeveloper** [comment]
This was closed in #305
