### ISSUE TITLE
Create a mechanism to allow unassociated kits to individuals

### ISSUE THREAD

**Issue by wasade** [qiime/qiime_web_app#308]
I'll be attending GET2013 and will be passing out kits to PGP participants. The issue is that we do not know who they are yet, so we cannot pre-associate barcodes with individuals.

**Comment by ElDeveloper** [comment]
This one should be closed right?

**Comment by douginator2000** [comment]
Yup!

On Fri, May 10, 2013 at 11:17 AM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> This one should be closed right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/308#issuecomment-17732822
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu
