### ISSUE TITLE
Poller: prevent multiple instances

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#31]
It may be possible to get two instances of the poller running by invoking from different python versions. Investigate if this is possible, and if so prevent it from happening. When the poller starts, it creates a PID file in /tmp. If it's not already happening, the poller should explicitly check for the existence of this file before starting. Possibly other checks as well.

**Comment by wasade** [comment]
this should not be possible with different versions as there is a pid file check. we should move that pid file to /var/run/lock (i believe that's the location). 

i'd _really_ like to see when the poller is dying so that it can be fixed...

**Comment by wasade** [comment]
There is already an explicit check for the pid file. If this is not working, is it possible to provide an exact example? We likely want to move the .pid out of /tmp and into /var/run/, however it does require some care with permissions.

**Comment by wasade** [comment]
I have not seen evidence of multiple pollers. It may be possible if /tmp is wiped, but I haven't seen evidence of that either given the timestamps on the stdout and stderr logs.
