### ISSUE TITLE
Question to add to FAQ

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#312]
People are confused that each sample has two cotton swabs:

"Also the directions on the package say "q tip," not "2 q tips" which are what I received in the glass sheathing. Why did I receive 4 in total (q tips) if the directions call for one?"

Please add an FAQ that explains that the two cotton swabs in each tube constitute a single sample, and that swabbing for that sample should be done with both swabs.

**Comment by adamrp** [comment]
Another question to add to the FAQ.

We have a kit for four samples, and we would like to collect and send them in at different times, say a week apart.  What is the best way to do this?

**Comment by adamrp** [comment]
For the second one, this is how I responded:

Thanks for checking with us.  You have two options:

1) Send us the samples as you collect them.  We will put them on ice and take care of them until we can process them.
2) Keep them in your freezer and send us all your samples at the same time.  If you choose this option, please note that you should avoid repeated freeze/thaw cycles (i.e., once they're frozen, keep them frozen).  This means that when you ship them (preferably overnight), you should keep them cold (e.g., with gel packs).

I recommend option 1 since there are fewer opportunities to make a mistake and you will get the best quality data out of your samples that way, but it does involve more postage.  It's up to you!

**Comment by ElDeveloper** [comment]
This was fixed in #314
