### ISSUE TITLE
Change "7-13" checkbox to radio

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#315]
There are two different parental consent forms, one for children 0-7 and one for children 7-13.  Would be good to change this to a radio button providing these two options

**Comment by adamrp** [comment]
In the meantime, can we change the label on the box so that it reads something like "This is a minor below the age of 13", because we have some users emailing us about sampling their child who is younger than 7, and right now it appears that there is no way to sign them up...

**Comment by ElDeveloper** [comment]
:+1:
