### ISSUE TITLE
Key for the map on index

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#321]
blue = participant
yellow = verified
green =

**Comment by douginator2000** [comment]
Meg, I'm noticing that the key looks a little funny - icons aren't lined up and they kinda look like a mapping point on the map itself. Maybe line them up and put a background in (like the div above, or even part of the login div itself?)

![Screen Shot 2013-04-11 at 2 57 02 PM](https://f.cloud.github.com/assets/608209/370195/a1a71378-a2ea-11e2-9a22-4a1428b4c821.png)

**Comment by douginator2000** [comment]
Oh, well that's bizarre. I refreshed the page and it looks fine. 
![Screen Shot 2013-04-11 at 2 59 53 PM](https://f.cloud.github.com/assets/608209/370203/d4824272-a2ea-11e2-87ba-dc69d102d5b3.png)

**Comment by douginator2000** [comment]
Closing this - looks like it was just a browser refresh/cache problem.
