### ISSUE TITLE
make changes with respect to privacy concerns

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#325]
We need to make a new table, change stored procedures, change ModPython code etc; we cannot have the personally identifiable information in the same table as the survey information, due to IRB concerns.

**Comment by adamrp** [comment]
This issue was resolved after discussions with IRB in which our current system was deemed acceptable.

**Comment by ElDeveloper** [comment]
Woohoo!

Yoshiki Vázquez-Baeza
