### ISSUE TITLE
Validation for AG admin tools

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#359]
"Add new participant" - Validate fields as we do on the AG forms:
- Email must be a valid email 
- Name, address, city, state, zip, country - all must be filled out (cannot be blank)

"Add new kit"
- Kit ID, password, Number of Swabs, verification - all must be filled out
- Number of Swabs must be a number

"Add new barcode"
- Must be filled out
- Must be only numeric
- Must be exactly 9 characters

"Edit participant"
- Same rules as add new participant

"Reassign barcode"
Nothing needs to be done

**Comment by douginator2000** [comment]
Also just added BW suppport - new admin link. If you can prettify/make the drop down consistent with whatever you're doing on the others, and also make sure that the text field is filled out that would be great.

**Comment by megalodonatron** [comment]
:rabbit:
