### ISSUE TITLE
gzipped SFF files do not work

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#36]
During processing, this error occurs:
cogent.parse.binary_sff.UnsupportedSffError: magic_number not
supported. (Expected 779314790, observed 529205256)

779314790 in hex is 0x2e736666 (".sff" in ASCII), the magic number that indicates an SFF file.
529205256 in hex is 0x1f8b0808, the magic number that indicates a gz file

Apparently, the cogent code does not work with gzipped files.

**Comment by wasade** [comment]
use gzip.open

**Comment by douginator2000** [comment]
Okay so this has been working in some cases. I've processed numerous
gzipped files - perhaps though they were all fastq? Maybe that's true -
haven't actually paid attention.

On Oct 23, 2012, at 1:00 PM, Daniel McDonald notifications@github.com
wrote:

use gzip.open

On Tue, Oct 23, 2012 at 12:58 PM, adamrp notifications@github.com wrote:

> During processing, this error occurs:
> cogent.parse.binary_sff.UnsupportedSffError: magic_number not
> supported. (Expected 779314790, observed 529205256)
> 
> 779314790 in hex is 0x2e736666 (".sff" in ASCII), the magic number that
> indicates an SFF file.
> 529205256 in hex is 0x1f8b0808, the magic number that indicates a gz file
> 
> Apparently, the cogent code does not work with gzipped files.
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/qiime/qiime_web_app/issues/36>.

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/issues/36#issuecomment-9713760.

**Comment by adamrp** [comment]
I think they must have all been fastq.gz, because one of the first things that happens in cogent.parse.binary_sff.parse_binary_sff is validate_common_header, which will cause it to fail right off the bat if it is a sff.gz.

Daniel's solution should be a quick fix here -- I just tested it on a file, and it appears to work.

Does either Qiime or Cogent have a method for testing whether a file is gzipped?  If not, we might want to add a function for that somewhere.  Where would it belong?

Suggest editing qiime.process_sff.py:
from gzip import open as gzip_open

then on lines 205 and 221, we should explicitly check if the file is gzipped (check if first two bytes are 0x1f8b indicating gzip, or if the first 4 bytes are 0x2E736666 indicating .sff), then use either gzip_open or regular-old open, respectively before passing the open file object to format_binary_sff_as_fna

**Comment by wasade** [comment]
qiime.util.qiime_open tests for a .gz extension and opens with gzip.open if
it exists, otherwise uses regular open. this should be pushed back into
cogent but the functionality isn't there (i was a bit surprised)

**Comment by adamrp** [comment]
Just for my own note-taking, the following functions in qiime.process_sff.py do not currently use qiime_open, and I am going to modify them to use it:

convert_Ti_to_FLX
make_flow_txt
make_fna
make_qual

Adam

**Comment by adamrp** [comment]
Made modifications that should allow processing of gzipped SFF files and made pull request on qiime; awaiting merge by Greg.

**Comment by douginator2000** [comment]
Nice thanks Adam.

On Wed, Oct 31, 2012 at 11:22 AM, adamrp notifications@github.com wrote:

> Made modifications that should allow processing of gzipped SFF files and
> made pull request on qiime; awaiting merge by Greg.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/36#issuecomment-9953709.

## 

Doug Wendel, PRA
University of Colorado at Boulder
Department of Chemistry and Biochemistry
Knight Lab

**Comment by adamrp** [comment]
Just an update on this: apparently, the code I wrote broke the test code in qiime (I didn't notice this because I didn't have SFF tools installed, so those tests were skipped and did not fail).  The code works fine if you're not using the SFF tools (and instead are using QIIME only, which recapitulates the same functionality).  Waiting to hear back from Greg on how best to handle this.

**Comment by douginator2000** [comment]
Any update on this adam?

**Comment by adamrp** [comment]
No not yet -- I haven't looked into whether or not the pipeline on the web
app uses the sff tools or the QIIME code.  If it's the latter, then it
should work fine.  If it's the former, it definitely won't work.

I will try to find some time tomorrow to look into it.

**Comment by adamrp** [comment]
run_process_sff_through_split_lib.py DOES pass --use_sfftools to process_sff.py

I'll test what happens if I remove --use_sfftools (using webdev)

**Comment by douginator2000** [comment]
Merged request and ran a study - fails on live. Adam will you look into this ASAP?

**Comment by adamrp** [comment]
The change I made uses is_gzip, which is something I committed to QIIME a while ago (in qiime.util.py) -- I thought those changes were on the live system.  I'll add the same function to run_process_sff_through_split_lib.py with a note that, whenever we DO update QIIME on the system, we should change it to use the function from qiime.util
