### ISSUE TITLE
Female Questions survey page

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#363]
Clicking the continue button appears to do nothing, and apparently (according to one user) sometimes throws a modpython error.  Clicking continue shows this in the javascript console:

american_gut.js:452
Uncaught TypeError: Cannot read property 'value' of undefined american_gut.js:452
verifyOptionalQuestionsamerican_gut.js:452
onclick

The mod python error is:

AttributeError: 'module' object has no attribute 'redirect'

**Comment by megalodonatron** [comment]
:rabbit:
