### ISSUE TITLE
allow users to change their password after authentication

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#367]
Once users have successfully logged in once, should allow them to change their password

**Comment by ElDeveloper** [comment]
Hey @douginator2000, would it be feasible if @RNAer and I pursued this one? Or do you think the current infrastructure will not make this change easy.

**Comment by douginator2000** [comment]
Sure, can do, though I would say this is a very low priority.

On Wed, Jun 19, 2013 at 12:13 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> Hey @douginator2000 https://github.com/douginator2000, would it be
> feasible if @RNAer https://github.com/RNAer and I pursued this one? Or
> do you think the current infrastructure will not make this change easy.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/367#issuecomment-19702697
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Should we target a different one then?

If so, @RNAer, can you pick a different task?
