### ISSUE TITLE
Fix WebDev

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#4]
The WebDev site is intended for the development and testing of newly available features, currently this doesn't work as supposed to, so a clean-up of the site is required.

**Comment by adamrp** [comment]
Can we close this issue?

**Comment by douginator2000** [comment]
Ya!

On Mon, Feb 25, 2013 at 4:03 PM, adamrp notifications@github.com wrote:

> Can we close this issue?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/4#issuecomment-14081995.

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu
