### ISSUE TITLE
Add new sampling photos into instruction workflow

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#401]
As the title says. Poo slathered swabs abound apparently when we don't really need that much ... "material". Posting the good/bad photos in the instructions would be very useful.
![photo 2](https://f.cloud.github.com/assets/608209/514905/9d154abe-be65-11e2-996f-d2e070dbcbc9.jpg)
![photo 1](https://f.cloud.github.com/assets/608209/514907/9d177ea6-be65-11e2-9ffa-27a33d5f8deb.jpg)
![photo 3](https://f.cloud.github.com/assets/608209/514906/9d16daaa-be65-11e2-9394-dea880e02b9f.jpg)
![photo 4](https://f.cloud.github.com/assets/608209/514908/9d183120-be65-11e2-910a-8833090e5dbe.jpg)
![photo 8](https://f.cloud.github.com/assets/608209/514909/9d23b63a-be65-11e2-988b-cdd6828f78fc.jpg)
![photo 5](https://f.cloud.github.com/assets/608209/514910/9d4d0864-be65-11e2-8d7a-f208bb4d263b.jpg)

**Comment by douginator2000** [comment]
Photos 1-3 are good, 4, 5, and 8 are way too poopy!

**Comment by megalodonatron** [comment]
This is done
