### ISSUE TITLE
wwwadmin search not showing a kit

### ISSUE THREAD

**Issue by wasade** [qiime/qiime_web_app#403]
The details associated with barcode 000003937 don't actually show up. Use the search interface on wwwadmin and search for it...

**Comment by douginator2000** [comment]
There seems to be a bug in search - lookin' at it now.

On Mon, May 20, 2013 at 5:39 PM, Daniel McDonald
notifications@github.comwrote:

> The details associated with barcode 000003937 don't actually show up. Use
> the search interface on wwwadmin and search for it...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/403
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by douginator2000** [comment]
Okay D, try that same search again. Found the issue.

On Mon, May 20, 2013 at 9:24 PM, Doug Wendel douginator2000@gmail.comwrote:

> There seems to be a bug in search - lookin' at it now.
> 
> On Mon, May 20, 2013 at 5:39 PM, Daniel McDonald <notifications@github.com
> 
> > wrote:
> > 
> > The details associated with barcode 000003937 don't actually show up. Use
> > the search interface on wwwadmin and search for it...
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/403
> > .
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edu

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by wasade** [comment]
Looks good, thanks @douginator2000
