### ISSUE TITLE
Unavailable tyvek bags

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#482]
Just received an e-mail from a french participant indicating that FedEx does not provide tyvek bags in France, the suggestion made there was to use a "clinical bag". I don't know the difference between these two, but it would be worth adding a note about this in the instructions.

**Comment by megalodonatron** [comment]
We should probably ask Gail first if that is acceptable.

**Comment by ElDeveloper** [comment]
Yeah @ackermag are there any restrictions regarding this?

**Comment by ackermag** [comment]
No - sounds like that is a good alternative.  IRB will have no problem

On Wed, Aug 21, 2013 at 11:18 AM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> Yeah @ackermag https://github.com/ackermag are there any restrictions
> regarding this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/482#issuecomment-23033910
> .

## 

Gail Ackermann
Knight Lab UCB 596
University of Colorado
Boulder

**Comment by ElDeveloper** [comment]
Fantastic!

**Comment by ElDeveloper** [comment]
This issue has been resolved.
