### ISSUE TITLE
Duplicate prokmsa ids

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#487]
Selecting all the studies listed below, will print the following traceback in the web portal. The meta-analysis is only trying to create an OTU table and a mapping file nothing else:

``` python
Submitted Meta-Analyses: 
    • Job 103383: COMPLETED_ERROR 
    • 
    • Output: Traceback (most recent call last): 
        File "/home/wwwuser//git/qiime_web_app/python_code/scripts/make_mapping_file_and_otu_table.py",

        line 89, in main() 
            File "/home/wwwuser//git/qiime_web_app/python_code/scripts/make_mapping_file_and_otu_table.py",
        line 86, in main jobs_to_start,taxonomy,tree_fp)
            File "/home/wwwuser/git/qiime_web_app/python_code/generate_mapping_and_otu_table.py",
        line 521, in write_mapping_and_otu_table otu_table_file_dir_db)
            File "/home/wwwuser/git/qiime_web_app/python_code/generate_mapping_and_otu_table.py",
        line 561, in write_otu_table
            raise ValueError, 'Duplicate prokmsa ids! - %s ' % sample_name1 ValueError: Duplicate prokmsa ids! - P.C.7.1.414758
```

The selected studies are the following:
- Ballor_saline_environments
- Berry_MA_pond_sediment_profiles
- Biddle_Ocean_Drilling_Program_Leg_201
- Biddle_Pavilion_Lake_microbialite
- Bowatte_NZ_FreeAirCarbonEnrichment
- Brazelton_Serpentinite_Seeps
- CaporasoIlluminaPNAS2011_5prime
- Caporaso_Glen_Canyon_soils
- Caporaso_illumina_time_series
- Caporaso_yellowstone_gradients
- Cary_NZTABS_antarctic_soil
- Catlin_Arctic_Survey_2010_L3
- Chu_Changbai_mountain_soils
- Chu_tibetan_lake_sediments
- Delsuc_microbi_ant
- Dubinsky_Hawaii_Kohala
- Ercolini_ObeseSaliva
- Ezenwa_Cape_Buffalo
- Forsman_swallow_egg_nest
- Friedman_arctic_peat_soil
- Gasser_MWC_catchment_microbes
- Gilbert_Bergen_mesocosm
- Gittel_CryoCARB_2_permafrost
- Grossart_German_lake_water_sediment
- Haig_WaterPurif_temp_spat
- Hofmockel_TempleTX_native_exotic_ppt_soils
- Hulth_Gullmarfjord_sediment
- Hultman_Geochemical_Landscapes_permafrost
- Jansson_Alaskan_fire_chrono_Tanana
- Jansson_LDRD_Biological_Carbon_Sequestration
- Jansson_Polluted_Polar_Coastal_Sediments
- Jurelevicius_Brazilian_Antarctic_contaminated_soils
- Jurelevicius_Rio_de_Janeiro_Coastline
- Jurelivicius_Antarctic_cleanup
- King_Kilauea_geothermal
- Knight_IQBIO_2013
- LaRoche_EPOCA_Svalbard2010_mesocosm
- Lipson_ice_wedge_polygon
- MacRaeCrerar_Mongolia_soil
- McMahon_MendotaLake_timeseries
- McMahon_Temperate_Bog_Lakes
- Metcalf_SanDiegoZoo_folivorus_primate
- Moore_Yucatan_cenotes
- MorganKiss_Dry_Valley_Lake_communities
- Myrold_Alder_Fir
- Myrold_Oregon_transect
- NEON_soils_EMP_Pilot
- Neufeld_Craibstone_pH_study_soil
- Peralta_birds
- Peralta_starlings
- Pfister_Intertidal_microbe_16s
- Rao_Thar_desert_microbes
- Rees_VulcanoIsland_seawaterMedSeA
- Robinson_English_ChannelL4_time_series_2009_2010
- Rockne_GreatLakesmicrobialdiversity
- Rohwer_Mission_Bay_sediment_viromes
- SKennedy_Cannabis_soils
- Spirito_Monensin_Cow_Hindgut
- Thomas_CMB_Australia_kelp_soi
- Wehrle_Panama_iguana- 

---

@wdwvt1 originally tried to create this meta-analysis. I was able to take a look at the mapping file that was generated but there was no OTU table. The total number of samples is around 15,000.

**Comment by ElDeveloper** [comment]
@wdwvt1 and @douginator2000 this issue seems to be resolved right?

**Comment by douginator2000** [comment]
As far as I'm aware, it's fixed.

On Thu, Aug 8, 2013 at 8:12 AM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> @wdwvt1 https://github.com/wdwvt1 and @douginator2000https://github.com/douginator2000this issue seems to be resolved right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/487#issuecomment-22325987
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Sweet! :shipit:
