### ISSUE TITLE
It is possible to not select a sample site on log sample

### ISSUE THREAD

**Issue by wasade** [qiime/qiime_web_app#490]
...and have the result stored as "Please select..."

**Comment by douginator2000** [comment]
Is this a question or desired functionality?

On Thu, Aug 8, 2013 at 8:24 AM, Daniel McDonald notifications@github.comwrote:

> ...and have the result stored as "Please select..."
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/490
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by mikewise** [comment]
I believe this is in response to the email thread that went around this
morning. We don't want users to be able to not select a sample site.
meaning, they can't proceed to log details unless they have completed all
of the fields. I think adam might have been working on this code.

**Comment by wasade** [comment]
This currently in place but not desired as it allows for the sample type to
be stored in the database as "Select sample type..." or whatever it is

**Comment by adamrp** [comment]
This was fixed via #491.
