### ISSUE TITLE
Agnostic link in the sidebar menu that says "Log Sample..."

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#568]
And provides 
-a dropdown of human, animal, environmental
-a dropdown of available sources

If there are no available sources it should have some sort of warning and direct the user to add sources

Should not be visible if 
-the kit is not verified
-no sources have been added

**Comment by teravest** [comment]
I agree logging the sample should be clearer on the website,  but if you
are responding to help account requests right now this faq
http://www.microbio.me/americangut/FAQ.psp#faq3 has the best instructions I
have seen.

**Comment by megalodonatron** [comment]
Yeah someone on the help account asked that I suggest to the dev team to have a better way of logging samples and I promised to open a ticket :rabbit:

**Comment by wasade** [comment]
Are these changes that you'd be able to implement?

**Comment by megalodonatron** [comment]
Yep, I was just about to start working on it.

**Comment by wasade** [comment]
Awesome, thanks
