### ISSUE TITLE
Change title of "Addendum" in the menu

### ISSUE THREAD

**Issue by adamrp** [qiime/qiime_web_app#570]
maybe something like "Help interpreting my results," which then brings the user to the addendum document

**Comment by megalodonatron** [comment]
:+1:

**Comment by megalodonatron** [comment]
Speaking of this sort of thing, the menu is getting kind of cluttered now and it might be better to have some top level category to keep things like
- AG 101
- Prelim results
- Addendum

Also the lefthand menu when you're logged out has completely different styling than when you're logged in, should probably make this consistent

**Comment by ElDeveloper** [comment]
:+1:

**Comment by adamrp** [comment]
I agree with all these suggestions.

**Comment by teravest** [comment]
I think this has been taken care of and can be closed.
