### ISSUE TITLE
Using popup messages for edit survey is possibly messed up in Chrome

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#578]
You can't edit a survey in chrome because the popup that you need to click ok to continue never shows up

The relevant error is:

```
Uncaught TypeError: Property 'alert' of object [object Object] is not a function 
```

**Comment by teravest** [comment]
I have been editing surveys in chrome all morning without an issue.

**Comment by megalodonatron** [comment]
Weird, it may be some plugin or popup blocker that I have.

**Comment by megalodonatron** [comment]
Can anyone else test this and see? I click the "edit" button after clicking on a participant from the human participants menu and nothing happens.

**Comment by ElDeveloper** [comment]
Not happening on my computer. Just tried it out with Chrome.

**Comment by megalodonatron** [comment]
K I'm closing it then, I suspect it's just my chrome but this should just be an FYI for any help account people who are saying that they can't start/edit surveys, as thats why I checked on this issue.

**Comment by ElDeveloper** [comment]
Oh, hmm that's odd. And the browser they are using is also Chrome? Just so we have some sort of documentation about this, I tested using 31.0.1650.63.

**Comment by megalodonatron** [comment]
This is their exact message:

---

I am unable to enter a new human source.  The directions included in my packet indicate that there should be an "Add Participant" option in the lefthand tool bar, but there is not.  Alternatively, I've tried clicking through the Human Source page, which says I'll be beginning now as soon as I click "Continue."  However, clicking continue does nothing.  I've tried in both Chrome and IE.

---

Which lead me to try and click around on different options and I noticed the edit issue in my chrome but not safari or ff.

**Comment by adamrp** [comment]
@teravest, do you mean you have been editing them in wwwadmin, or on the
participant site via the edit survey link?

**Comment by adamrp** [comment]
@teravest never mind -- I didn't see all these other messages in my inbox in gmail, but now I see there's been a whole discussion here!  Anyways, I also do not have any issues editing a survey, nor do I have any problem clicking "continue" on the Add Human Source page (no javascript errors, either). I have the exact same version of chrome as Yoshiki, however -- perhaps this person has an older version?
