### ISSUE TITLE
Some samples show results yet haven't been marked as received

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#579]
This should be impossible because you can only have sequenced and analyzed the sample if it was received. Is this an artifact from before the barcode scanner util? If so, all samples that have results should automatically be marked as received.

**Comment by adamrp** [comment]
likely an artifact, yes -- I agree that all samples that have results
should be marked as received.  If there are no objections, I can do this
tonight or tomorrow.

Adam

**Comment by ElDeveloper** [comment]
:+1:

**Comment by adamrp** [comment]
Done.
