### ISSUE TITLE
Your results are ready link won't work in all browsers

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#589]
I have not been able to confirm this myself but a lot of people is reporting problems with this feature. The problem seems to indicate that the link takes them either to the login site or to the home page of the participant website. 

I would be ok with closing this issue if we can verify in a couple browsers IE, Opera, Firefox, etc that this is indeed working for all of these browser.

**Comment by adamrp** [comment]
It works for me, as long as I only have one tab open accessing the site.
 However if I open one tab, see the link, then open another tab, then click
the link, it brings me to the login page.

What do you mean by the "homepage of the participant"?

**Comment by ElDeveloper** [comment]
"homepage of the participant" -> the site that they are taken to once they successfully login.

Thanks,

Yoshiki.

**Comment by adamrp** [comment]
It sounds like a session thing resulting from having more than one tab
open, but I obviously can't be certain since I can't replicate the issue
exactly.  Can anyone else test?

**Comment by teravest** [comment]
This has been reported in Explorer, Safari and Chrome.  However one person said it worked in Chrome but not Explorer.  I asked the person who said it didn't work in Chrome to try updating Chrome.

**Comment by ElDeveloper** [comment]
Cool, might be a good idea to try and ask them for the version of the browser that they are using.

@wasade, @adamrp, @JWDebelius, just a heads up that this has consistently been a known issue for some people.

**Comment by teravest** [comment]
So far Firefox is the only browser not to be complained about.

**Comment by ElDeveloper** [comment]
Seems like a way to reproduce the problem is to use OS X 10.6.8 and Safari 5.1.10.

![issue_589](https://f.cloud.github.com/assets/375307/1965350/2ed1e990-82b9-11e3-944a-c7096c99768d.png)

**Comment by adamrp** [comment]
I think this _might_ be due to the fact that some forms (e.g., sample_overview_000000001) are defined in menu.psp and the same name is used on results_portal.psp.  I'm going to change the name of the forms on results_portal.psp.  @ElDeveloper, do you have system to test on?  How did you generate the screenshot above?

**Comment by ElDeveloper** [comment]
I generated the screenshot using the tower in the Skype room, has both 10.6.8 and 5.1.10. Let me know if you need any help.

**Comment by adamrp** [comment]
Okay, thanks -- I'm going to deploy a potential fix to webdev and test it
on the tower.  Hopefully I can get that javascript error to stop popping
up, and hopefully I fixing that will fix the problem!

**Comment by ElDeveloper** [comment]
Great, thanks!

**Comment by wasade** [comment]
Thanks!

**Comment by teravest** [comment]
We may have found a work around for this.  From my testing on the tower,
 when we try to recreate this, the links do not work from the participant
home screen, but they work from other pages.

**Comment by ElDeveloper** [comment]
Emily could you draft some workaround instructions and send those to the AG list? Such that anyone helping the current AG Master is aware of the problem and the temporary solution.

Thanks!

Yoshiki.

**Comment by teravest** [comment]
Yes I can do that, before I do that does anyone have any objection to me
asking the guy who seemed most competent in his response to test the work
around for us?

**Comment by ElDeveloper** [comment]
That actually would be a great idea! Hopefully he'll have some spare time to help us!

Yoshiki.

**Comment by teravest** [comment]
I was just looking into this and I cannot get the error to appear on webdev from the tower.  Could it have been fixed in a pull request that hasn't been merged yet?  Any ideas?

**Comment by ElDeveloper** [comment]
Huh? So using webdev.microbio.me in the tower under Safari will work just fine?

Yoshiki.

**Comment by teravest** [comment]
Yes, using webdev on the tower works fine.   I think some of Megs changes
got deployed on webdev but not on live, but I could be wrong.

**Comment by ElDeveloper** [comment]
@meganap, @adamrp, could you guys confirm this?

Thanks!

Yoshiki.

**Comment by adamrp** [comment]
In class right now, but I can test later, hopefully.  @teravest, you can
use git log to check out the revision history to see what was merged and
compare that to the git log output on the live server.

**Comment by teravest** [comment]
@adamrp did you put your fix on webdev?  Here is the webdev git log
commit 42a4025e7bf7be210308d3a4e30bf4af420489a4 (HEAD, refs/heads/issue_589)
Merge: 78b92d1 20efe75
Author: wwwdevuser wwwdevuser@microbio.me
Date:   Tue Jan 21 12:01:47 2014 -0700

```
Merge branch 'issue_589' of
```

https://github.com/adamrp/qiime_web_appinto issue_589

commit 20efe7513972c9dcb64f78fc6a2a552d2c729eab
Author: Adam Robbins-Pianka adam.robbinspianka@colorado.edu
Date:   Tue Jan 21 12:01:27 2014 -0700

```
Move form code on result_portal
```

commit 78b92d13b658db1985a64f598dabe766d78346a0
Merge: 1e2a8f7 f5947c0
Author: wwwdevuser wwwdevuser@microbio.me
Date:   Tue Jan 21 11:59:32 2014 -0700

```
Merge branch 'issue_589' of
```

https://github.com/adamrp/qiime_web_appinto issue_589

commit f5947c0795bdc203c591179afa4c3dbd87980bcc
Author: Adam Robbins-Pianka adam.robbinspianka@colorado.edu
Date:   Tue Jan 21 11:59:10 2014 -0700

```
Change form name on result_portal
```

commit 1e2a8f712896eb2b86f8abd76f82f3dcfbdbf591 (refs/heads/master)
Merge: 427d96d c9e8e8c
Author: wwwdevuser wwwdevuser@microbio.me
Date:   Tue Jan 21 11:57:56 2014 -0700

```
Merge branch 'master' of git://github.com/qiime/qiime_web_app
```

commit c9e8e8c1adbd8f976ce1bc95e9be68b92fa9c234
Merge: 5ff1464 6cb7e88
Author: Yoshiki Vázquez Baeza yoshiki89@gmail.com
Date:   Fri Jan 17 12:21:58 2014 -0800

```
Merge pull request #591 from adamrp/issue_590

Add disclaimer to top of taxa summary
```

commit 6cb7e88104ab18d741682088d1d44c566e0b08c8
Author: Adam Robbins-Pianka adam.robbinspianka@colorado.edu
Date:   Fri Jan 17 13:03:00 2014 -0700

```
Add disclaimer to top of taxa summary

Fixes #590
```

**Comment by adamrp** [comment]
That is indeed the branch on my fork that would fix the problem; I couldn't
test it yesterday because Yoshiki and Antonio were using the tower at the
time, but if it works, that's great!

**Comment by ElDeveloper** [comment]
Ah, fantastic!! What a happy accident!
