### ISSUE TITLE
assign kit to project

### ISSUE THREAD

**Issue by teravest** [qiime/qiime_web_app#608]
We need a WWWadmin function to assign all the barcodes in a kit to a specific project.

To do this I think I need 2 new stored procedures
get_barcodes_by_kit_id  and set_barcode_proj_type.

On the WWWadmin page, should this be under edit existing kit or should it be a new  link?  Or both?  What is more functional?  

Any opinions?  

I am hoping to get this done this week, we will see how jury duty goes, I have to report in the morning.

**Comment by adamrp** [comment]
This sounds good, thanks, Emily! I think the functionality can go in the
edit existing kit section.  We also probably want to put an option in the
"Add New Kit" section so you can select the project when creating a kit.

**Comment by teravest** [comment]
Thats a good idea,

the only problem with that is when you create a kit, it doesn't have any
barcodes in it.
My understanding of the current workflow is
Create kit
create barcode
and barcode to kit
@wasada is that correct?

Right now all new barcodes are created under "American Gut Project"  that
is hardcoded in the stored procedure to create a new barcode.

We would have to change the assign barcode to kit function to assign the
barcode to the project associated with the kit, but in that case we would
have to associate kits with projects somewhere in the DB, currently it is
only samples(barcodes).

**Comment by adamrp** [comment]
Do other projects even have kits?  Or is AG the only project that has kits
comprising multiple barcodes?

**Comment by teravest** [comment]
As far as I know kits are AG specific, but I'm not sure.

**Comment by teravest** [comment]
Fixed in #612
