### ISSUE TITLE
Add checkmark asking if people want results

### ISSUE THREAD

**Issue by teravest** [qiime/qiime_web_app#671]
This was brought up in the AG meeting today.  It would be good to ask people they want their paper results before sending them and track that info in the database.

**Comment by rob-knight** [comment]
Specifically, idea is to make it opt-in for paper certificate.

On Apr 7, 2014, at 11:09 AM, teravest <notifications@github.com<mailto:notifications@github.com>> wrote:

This was brought up in the AG meeting today. It would be good to ask people they want their paper results before sending them and track that info in the database.

**Comment by adamrp** [comment]
After discussions between Jeff Leach and @rob-knight via email, it looks like we do not need this checkbox.
