### ISSUE TITLE
Barcode images 

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#680]
We haven't updated the images that show the barcodes on the main user interface thus showing broken links for people when they login.

**Comment by adamrp** [comment]
Ah, yeah, that's a really good point.  Where are these images? It's really simple - just have to move them to the web server. @wasade, do you know when these images are generated and where I might pull them from?

**Comment by wasade** [comment]
They're generated from the site we punch for the barcodes. Is the directory
of images (
https://github.com/qiime/qiime_web_app/tree/master/www/americangut/img/barcodes)
not up to date? If not, I'll need to dig around to find where the missing
ones are, but I thought I pushed them

**Comment by teravest** [comment]
these stop at 13672, we are up to at least 16xxx now.

**Comment by wasade** [comment]
I'll dig

**Comment by wasade** [comment]
what about if we just stop displaying the barcode images?

**Comment by ElDeveloper** [comment]
That's an option, another one-off option would be to generate a bunch of them and not worry about them for a while, though I don't know if this is easy/hard.

**Comment by adamrp** [comment]
I'm fine with just dropping them -- currently, it is a checkbox next to a
text version of the barcode, next to a picture of the number -- is it
really necessary?

**Comment by teravest** [comment]
is any human eye going to be able to match up a barcode image anyway :)

**Comment by ElDeveloper** [comment]
Don't think so, we probably should "trick" the user by showing a generic barcode and the numbers bellow.

**Comment by adamrp** [comment]
...Or develop a new package for producing barcodes using ASCII art. Genius.

**Comment by teravest** [comment]
Can each barcode should have a doge in it ;)

**Comment by wasade** [comment]
+1, much image
