### ISSUE TITLE
Package-ify the web app

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#69]
The entire qiime_web_app project should be organized as a package. This would help in organization and readability of code quite a bit. It would also simplify path and import statements in the OS and in code.

**Comment by ElDeveloper** [comment]
I think this is very related to what was commented in issue #40 if so, we should close this issue and just leave the previous one open.

Also: yes, this is definitely needed, I agree.

**Comment by douginator2000** [comment]
You are so correct sir. I searched on "package" and found no results, but that is the same issue. Closing this.
