### ISSUE TITLE
Obsolete version of ENVO

### ISSUE THREAD

**Issue by pbuttigieg** [qiime/qiime_web_app#716]
Greetings,
It seems you're using an obsolete version of envo-basic.obo. You can access the latest release version here: http://purl.obolibrary.org/obo/subsets/envo-basic.obo

If you have any questions, please post on our issue tracker. This is currently on Google code (https://code.google.com/p/envo/issues) but will soon move to GitHub.

**Comment by ElDeveloper** [comment]
Hello @pbuttigieg, thanks for the heads up, but this project has been deprecated in favor of [Qiita: spot patterns](http://github.com/biocore/qiita). I've reposted [this issue there](https://github.com/biocore/qiita/issues/907) where more people involved with the project will be able to follow-up.
