### ISSUE TITLE
"jobs2" seems a typo in www/select_study_task.psp

### ISSUE THREAD

**Issue by RNAer** [qiime/qiime_web_app#89]
It is in the block between line 255 and 259:
    if is_admin == 1:
        jobs2 = data_access.getJobInfo(study_id, 12)
        if len(jobs) > 0:
            # indent

The variable is not used anywhere. It is probably supposed to be "jobs"

**Comment by douginator2000** [comment]
Fixed - corrects a small bug on the study page in which the bullet item for database loading jobs would appear prior to a list of those jobs being available.
