### ISSUE TITLE
Factor sequence deletion code into job

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#9]
Remove the sequence deletion code from the PSP file and factor into a new or existing job (possible add it to the processing job).

**Comment by adamrp** [comment]
This will have to wait until we have development environments (and/or webdev is fixed), since i wouldn't want to modify the production code on www.

**Comment by adamrp** [comment]
Thought that "close" meant close the thread... woops

**Comment by douginator2000** [comment]
I've moved the delete code into the job (and also added code to remove the old processed_data_ directories when processing). I'll deploy/test as soon as the blocking task of porting www's references to GIT repositories (currently pointed to SVN repos) is resolved.

**Comment by douginator2000** [comment]
Committed and tested. Seems to be working.. closing issue now.
